FROM tensorflow/tensorflow:1.14.0-gpu-py3

RUN apt-get update && apt-get install -y \
	zsh \
	git \
	libsndfile1 \
	wget

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN pip install librosa matplotlib pandas progressbar torch docopt==0.6.2 python-levenshtein recordtype ruamel.yaml requests pyroomacoustics

WORKDIR /home/xiaowei/
